[project]
name = "trip-assistant"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<3.14"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
